export default {
  changesSaved: 'Changes Saved!',
  connectionError: 'Connection error',
  currentExpirationDays: 'Current expiration days: ',
  setDataExpirationDays: 'Set expiration days quantity',
  days: 'Days',
  dataExpirationDescription:
    'You can configure for how many days the data is considered valid. After that time it will be erased and re-downloaded from the server',
  email: 'Email',
  errorFetching: 'Oops, something went wrong while fetching movies!',
  emailHint: 'Enter your email',
  home: 'Home',
  homeMessage: 'Welcome',
  loading: 'Loading',
  login: 'Login',
  logout: 'Logout',
  password: 'Password',
  passwordHint: 'Enter your password',
  profile: 'Profile',
  profileMessage:
    'And this one has a nav, but with a different color than the login.',
  myList: '+ My List',
  noMoviesFound: 'Sorry\nThere are no movies matching the entered criteria',
  removeFromMyList: '✓ Remove from my list',
  releaseDate: 'Release date',
  save: 'save changes',
  searchPlaceholder: 'Search for a movie that you love...',
};
